apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s1
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-d1a33128-a89c-419d-965f-d5179bec53c9
      eventName: github-d1a33128-a89c-419d-965f-d5179bec53c9
      eventSourceName: s1
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: hello1
        conditions: github-d1a33128-a89c-419d-965f-d5179bec53c9
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: s1-hello1-
              spec:
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                workflowTemplateRef:
                  name: workflow-template-hello1
          parameters: []
