apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sensor-fors1
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-821f7ff4-8586-403e-ab3c-427cdc1345a2:
      events:
        - push
      repositories:
        - owner: maryiaCodefresh
          names:
            - testticket
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/gitops/sensor-fors1/github-821f7ff4-8586-403e-ab3c-427cdc1345a2
        url: https://651bd573a935bf255bb155c2-aws-runtime.tunnels.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
