apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-fors1
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-821f7ff4-8586-403e-ab3c-427cdc1345a2
      eventName: github-821f7ff4-8586-403e-ab3c-427cdc1345a2
      eventSourceName: sensor-fors1
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: hello1
        conditions: github-821f7ff4-8586-403e-ab3c-427cdc1345a2
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sensor-fors1-hello1-
              spec:
                arguments:
                  parameters:
                    - name: message
                      value: hello1 world s1
                workflowTemplateRef:
                  name: workflow-template-submittable
          parameters: []
